version: '3.7'
services:
    db:
        image: mariadb:latest
        container_name: mudi_mariadb
        restart: always
        environment:
            MYSQL_DATABASE: mudi
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        expose: 
            - "3306"
        networks: 
         - production-network
networks:
    production-network:
        driver: bridge
        name: production-network